### Get all Students
GET http://localhost:4004/odata/v4/catalog/Student
Accept: application/json

###

### Get a Student by key
GET http://localhost:4004/odata/v4/catalog/Student(email='alice.wonderland@example.com')
Accept: application/json


### Update a Student (via UpdateStudent)
PATCH http://localhost:4004/odata/v4/catalog/UpdateStudent(email='alice.wonderland@example.com')
Content-Type: application/json

{
  "first_name": "UpdatedName"
}

###

### Insert a single Student
POST http://localhost:4004/odata/v4/catalog/InsertStudent
Content-Type: application/json

{
  "email": "new.student@example.com",
  "first_name": "New",
  "last_name": "Student",
  "date_sign_up": "2025-08-26"
}

### Insert multiple Students
POST http://localhost:4004/odata/v4/catalog/insertManyStudents
Content-Type: application/json

{
  "students": [
    {
      "email": "multi.one@example.com",
      "first_name": "Multi",
      "last_name": "One",
      "date_sign_up": "2025-08-26"
    },
    {
      "email": "multi.two@example.com",
      "first_name": "Multi",
      "last_name": "Two",
      "date_sign_up": "2025-08-26"
    }
  ]
}

###

### DELETE a Student
DELETE http://localhost:4004/odata/v4/catalog/DeleteStudent(email='new.student@example.com')

### Get CustomStudent
GET http://localhost:4004/odata/v4/catalog/CustomGetStudent
Accept: application/json